package com.spq.client.web;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

import com.spq.client.data.Signup;
import com.spq.client.data.User;
import com.spq.client.data.Purchase;
import com.spq.client.data.Rating;
import com.spq.client.data.RatingInfo;
import com.spq.client.data.Item;
import com.spq.client.data.Offer;
import com.spq.client.data.OfferCreator;
import com.spq.client.data.PaginatedResponse;
import com.spq.client.data.Pet;
import com.spq.client.data.Ad;
import com.spq.client.data.Category;
import com.spq.client.data.ChatMessage;
import com.spq.client.data.ChatRoomInfo;
import com.spq.client.data.Clothes;
import com.spq.client.data.Electronics;
import com.spq.client.data.Entertainment;
import com.spq.client.data.Home;


import java.util.List;
import java.util.Map;

public interface IVintedServiceProxy {
    public void createUser(Signup user);
	public Long login(String email, String password);
	public PaginatedResponse<Item> getItems(Long token,int page, String type);
	public PaginatedResponse<Item> getClothesByCategory(Long token, int page, Category category);
	public Item getItemById(Long id);
	public List<Clothes> getClothes(long token);
	public List<Clothes> getClothesByCategory(Category category, long token);
	public List<Electronics> getElectronics(long token);
	public List<Home> getHomeItems(long token);
	public List<Pet> getItemsForPet(long token);
	public List<Entertainment> getItemsForEntertainment(long token);
	public void logout(long token);
	public Purchase createPurchase(long token, Purchase purchase);
	public List<Purchase> createPurchases(long token, List<Purchase> purchases);
	public boolean processPayment(long purchaseId, String paymentMethod, long token);
	public boolean processPayments(List<Long> purchaseIds, String paymentMethod, long token);
	public void deleteUser(long token);
	public void updateUser(long token, String name, String surname, String description, MultipartFile profileImage);
	public User getUser(long id, long token);
	public Long getUserIdFromToken(Long token);
	public void uploadItem(long token, String title, String description, String category, float price, String brand, String size, String clothCategory, String clothingType, String species, String homeType, String electronicsType, String entertainmentType, List<MultipartFile> images);
	public long uploadItemData(long token, String title, String description, String category, float price, String brand, String size, String clothCategory, String clothingType, String species, String homeType, String electronicsType, String entertainmentType);
	public void uploadItemImage(long token, List<MultipartFile> images);
	public List<Item> getCartItems(Long token);
	public void addItemToCart(Long token, Long itemId);
	public void removeItemFromCart(Long token, Long itemId);
	public List<Item> getWishlistItems(Long token);
	public void addItemToWishlist(Long token, Long itemId);
	public void removeItemFromWishlist(Long token, Long itemId);
	public User getUserByItemId(Long itemId);
	public Purchase getPurchaseById(Long token, Long purchaseId);
	public List<Item> getUserItems(Long userId);
	public User getSeller(Item item);
	public void deletePurchase(Long token, Long purchaseId);
	public void deleteItem(Long token, Long itemId);
	public void followUser(Long token, Long targetUserId);
	public void unfollowUser(Long token, Long targetUserId);
	public List<User> getFollowers(Long targetUserId);
	public List<User> getFollowing(Long targetUserId);
	public PaginatedResponse<Item> searchItems(Long token, String search, int page, String type);
	public User getUserByUsername(String username, Long token);
	public List<Item> getUserItems(Long userId, Long token);
	public void createChatRoom(long buyerId, long sellerId, long itemId);
	public List<ChatRoomInfo> getChatRoomsForUser(long userId);
	public List<ChatMessage> getMessagesForChatRoom(Long chatRoomId);
	public Offer getOfferById(Long id);
	public Offer createOffer(OfferCreator offer, long token);
	public Map<String, Offer> updateOfferStatus(Long id, String status);
	public List<Offer> getOffersByItem(Long itemId, Long token);
	public ResponseEntity<Void> addRating(Rating rating, Long token);
	public List<RatingInfo> getRatingsForUser(long userId);
	public Offer acceptOffer(Long id);
	public Offer rejectOffer(Long id);
	public PaginatedResponse<User> searchUsers(Long token, String search, int page);
	public List<Item> getRecommendedItems(Long itemId, Long token);
	public List<Ad> getAllAds();
	public Ad getAdById(Long token, Long id);
	public void uploadAd(Long token, String title, String description, MultipartFile image);
	public void uploadAdImage(Long adId, MultipartFile image);
	public long uploadAdData(Long token, String title, String description);
}
