package com.spq.vinted.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

public class MessageTest {

    private ChatRoom chatRoom;
    private User sender;
    private Offer offer;

    @BeforeEach
    void setUp() {
        chatRoom = new ChatRoom();
        chatRoom.setId(1L);

        sender = new User();
        sender.setId(100L);
        sender.setUsername("testSender");

        offer = new Offer();
        offer.setId(50L);
    }

    @Test
    public void testNoArgsConstructor() {
        Message message = new Message();
        
        assertNull(message.getId());
        assertNull(message.getChatRoom());
        assertNull(message.getSender());
        assertNull(message.getContent());
        assertNull(message.getTimestamp());
        assertNull(message.getOffer());
    }

    @Test
    public void testThreeArgsConstructor() {
        String content = "Hello, this is a test message";
        
        Message message = new Message(chatRoom, sender, content);
        
        assertNull(message.getId()); // ID is generated by database
        assertEquals(chatRoom, message.getChatRoom());
        assertEquals(sender, message.getSender());
        assertEquals(content, message.getContent());
        assertNotNull(message.getTimestamp());
        assertTrue(message.getTimestamp().isBefore(LocalDateTime.now().plusSeconds(1)));
        assertTrue(message.getTimestamp().isAfter(LocalDateTime.now().minusSeconds(1)));
        assertNull(message.getOffer());
    }

    @Test
    public void testFourArgsConstructor() {
        String content = "This is an offer message";
        
        Message message = new Message(chatRoom, sender, content, offer);
        
        assertNull(message.getId()); // ID is generated by database
        assertEquals(chatRoom, message.getChatRoom());
        assertEquals(sender, message.getSender());
        assertEquals(content, message.getContent());
        assertNotNull(message.getTimestamp());
        assertTrue(message.getTimestamp().isBefore(LocalDateTime.now().plusSeconds(1)));
        assertTrue(message.getTimestamp().isAfter(LocalDateTime.now().minusSeconds(1)));
        assertEquals(offer, message.getOffer());
    }

    @Test
    public void testSettersAndGetters() {
        Message message = new Message();
        
        Long id = 1L;
        String content = "Test message content";
        LocalDateTime timestamp = LocalDateTime.now();
        
        message.setId(id);
        message.setChatRoom(chatRoom);
        message.setSender(sender);
        message.setContent(content);
        message.setTimestamp(timestamp);
        message.setOffer(offer);
        
        assertEquals(id, message.getId());
        assertEquals(chatRoom, message.getChatRoom());
        assertEquals(sender, message.getSender());
        assertEquals(content, message.getContent());
        assertEquals(timestamp, message.getTimestamp());
        assertEquals(offer, message.getOffer());
    }

    @Test
    public void testMessageTypeEnum() {
        Message.MessageType[] types = Message.MessageType.values();
        assertEquals(2, types.length);
        assertEquals(Message.MessageType.OFFER, Message.MessageType.valueOf("OFFER"));
        assertEquals(Message.MessageType.TEXT, Message.MessageType.valueOf("TEXT"));
    }

    @Test
    public void testGetTypeWithOffer() {
        Message message = new Message();
        message.setOffer(offer);
        
        assertEquals(Message.MessageType.OFFER, message.getType());
    }

    @Test
    public void testGetTypeWithoutOffer() {
        Message message = new Message();
        message.setOffer(null);
        
        assertEquals(Message.MessageType.TEXT, message.getType());
    }

    @Test
    public void testSetTypeOffer() {
        Message message = new Message();
        message.setType(Message.MessageType.OFFER);
        
        assertNotNull(message.getOffer());
        assertEquals(Message.MessageType.OFFER, message.getType());
    }

    @Test
    public void testSetTypeText() {
        Message message = new Message();
        message.setOffer(offer); // Set an offer first
        message.setType(Message.MessageType.TEXT);
        
        assertNull(message.getOffer());
        assertEquals(Message.MessageType.TEXT, message.getType());
    }

    @Test
    public void testTypeSwitching() {
        Message message = new Message();
        
        // Start with TEXT type
        message.setType(Message.MessageType.TEXT);
        assertEquals(Message.MessageType.TEXT, message.getType());
        assertNull(message.getOffer());
        
        // Switch to OFFER type
        message.setType(Message.MessageType.OFFER);
        assertEquals(Message.MessageType.OFFER, message.getType());
        assertNotNull(message.getOffer());
        
        // Switch back to TEXT type
        message.setType(Message.MessageType.TEXT);
        assertEquals(Message.MessageType.TEXT, message.getType());
        assertNull(message.getOffer());
    }

    @Test
    public void testTimestampIsSetInConstructor() {
        // Test that timestamp is set automatically when using constructors
        Message message1 = new Message(chatRoom, sender, "Test");
        assertNotNull(message1.getTimestamp());
        
        Message message2 = new Message(chatRoom, sender, "Test", offer);
        assertNotNull(message2.getTimestamp());
    }
}