package com.spq.vinted.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

public class OfferTest {

    private User sender;
    private User receiver;
    private Item item;
    private ChatRoom chatRoom;

    @BeforeEach
    void setUp() {
        sender = new User();
        sender.setId(1L);
        sender.setUsername("sender");

        receiver = new User();
        receiver.setId(2L);
        receiver.setUsername("receiver");

        item = new Clothes(); // Assuming Clothes extends Item
        item.setId(100L);
        item.setTitle("Test Item");

        chatRoom = new ChatRoom();
        chatRoom.setId(50L);
    }

    @Test
    public void testNoArgsConstructor() {
        Offer offer = new Offer();
        
        assertNull(offer.getId());
        assertNull(offer.getSender());
        assertNull(offer.getReceiver());
        assertNull(offer.getItem());
        assertNull(offer.getPrice());
        assertNull(offer.getStatus());
        assertNull(offer.getChat());
        assertNull(offer.getCreatedAt());
    }

    @Test
    public void testAllArgsConstructor() {
        Double price = 50.99;
        Offer.OfferStatus status = Offer.OfferStatus.PENDING;
        
        Offer offer = new Offer(sender, receiver, item, price, status, chatRoom);
        
        assertNull(offer.getId()); // ID is generated by database
        assertEquals(sender, offer.getSender());
        assertEquals(receiver, offer.getReceiver());
        assertEquals(item, offer.getItem());
        assertEquals(price, offer.getPrice());
        assertEquals(status, offer.getStatus());
        assertEquals(chatRoom, offer.getChat());
        assertNotNull(offer.getCreatedAt());
        assertTrue(offer.getCreatedAt().isBefore(LocalDateTime.now().plusSeconds(1)));
        assertTrue(offer.getCreatedAt().isAfter(LocalDateTime.now().minusSeconds(1)));
    }

    @Test
    public void testSettersAndGetters() {
        Offer offer = new Offer();
        
        Long id = 1L;
        Double price = 75.50;
        Offer.OfferStatus status = Offer.OfferStatus.ACCEPTED;
        LocalDateTime createdAt = LocalDateTime.now();
        
        offer.setId(id);
        offer.setSender(sender);
        offer.setReceiver(receiver);
        offer.setItem(item);
        offer.setPrice(price);
        offer.setStatus(status);
        offer.setChat(chatRoom);
        offer.setCreatedAt(createdAt);
        
        assertEquals(id, offer.getId());
        assertEquals(sender, offer.getSender());
        assertEquals(receiver, offer.getReceiver());
        assertEquals(item, offer.getItem());
        assertEquals(price, offer.getPrice());
        assertEquals(status, offer.getStatus());
        assertEquals(chatRoom, offer.getChat());
        assertEquals(createdAt, offer.getCreatedAt());
    }

    @Test
    public void testOfferStatusEnum() {
        Offer.OfferStatus[] statuses = Offer.OfferStatus.values();
        assertEquals(3, statuses.length);
        assertEquals(Offer.OfferStatus.PENDING, Offer.OfferStatus.valueOf("PENDING"));
        assertEquals(Offer.OfferStatus.ACCEPTED, Offer.OfferStatus.valueOf("ACCEPTED"));
        assertEquals(Offer.OfferStatus.REJECTED, Offer.OfferStatus.valueOf("REJECTED"));
    }

    @Test
    public void testToString() {
        Offer offer = new Offer(sender, receiver, item, 50.0, Offer.OfferStatus.PENDING, chatRoom);
        offer.setId(1L);
        offer.setCreatedAt(LocalDateTime.of(2023, 1, 1, 12, 0));
        
        String toString = offer.toString();
        
        assertTrue(toString.contains("id=1"));
        assertTrue(toString.contains("sender=1"));
        assertTrue(toString.contains("receiver=2"));
        assertTrue(toString.contains("item=100"));
        assertTrue(toString.contains("price=50.0"));
        assertTrue(toString.contains("status=PENDING"));
        assertTrue(toString.contains("chat="));
        assertTrue(toString.contains("createdAt=2023-01-01T12:00"));
    }

    @Test
    public void testToStringWithNullValues() {
        Offer offer = new Offer();
        
        // Este test fallará si toString() intenta acceder a propiedades de objetos nulos
        assertThrows(NullPointerException.class, () -> {
            offer.toString();
        });
    }

    @Test
    public void testUpdateOfferStatus() {
        Offer offer = new Offer(sender, receiver, item, 50.0, Offer.OfferStatus.PENDING, chatRoom);
        
        assertEquals(Offer.OfferStatus.PENDING, offer.getStatus());
        
        offer.setStatus(Offer.OfferStatus.ACCEPTED);
        assertEquals(Offer.OfferStatus.ACCEPTED, offer.getStatus());
        
        offer.setStatus(Offer.OfferStatus.REJECTED);
        assertEquals(Offer.OfferStatus.REJECTED, offer.getStatus());
    }

    @Test
    public void testUpdatePrice() {
        Offer offer = new Offer(sender, receiver, item, 50.0, Offer.OfferStatus.PENDING, chatRoom);
        
        assertEquals(50.0, offer.getPrice());
        
        offer.setPrice(75.0);
        assertEquals(75.0, offer.getPrice());
    }
}