var dir_e23da77fcde3117c6f62f7d63d527fb8 =
[
    [ "Ad.java", "_ad_8java.html", "_ad_8java" ],
    [ "Category.java", "_category_8java.html", "_category_8java" ],
    [ "ChatRoom.java", "_chat_room_8java.html", "_chat_room_8java" ],
    [ "Clothes.java", "_clothes_8java.html", "_clothes_8java" ],
    [ "ClothesSize.java", "_clothes_size_8java.html", "_clothes_size_8java" ],
    [ "ClothesType.java", "_clothes_type_8java.html", "_clothes_type_8java" ],
    [ "Electronics.java", "_electronics_8java.html", "_electronics_8java" ],
    [ "ElectronicsType.java", "_electronics_type_8java.html", "_electronics_type_8java" ],
    [ "Entertainment.java", "_entertainment_8java.html", "_entertainment_8java" ],
    [ "EntertainmentType.java", "_entertainment_type_8java.html", "_entertainment_type_8java" ],
    [ "Home.java", "_home_8java.html", "_home_8java" ],
    [ "HomeType.java", "_home_type_8java.html", "_home_type_8java" ],
    [ "Item.java", "_item_8java.html", "_item_8java" ],
    [ "Message.java", "_message_8java.html", "_message_8java" ],
    [ "Offer.java", "_offer_8java.html", "_offer_8java" ],
    [ "Pet.java", "_pet_8java.html", "_pet_8java" ],
    [ "Purchase.java", "_purchase_8java.html", "_purchase_8java" ],
    [ "Rating.java", "_rating_8java.html", "_rating_8java" ],
    [ "Shipment.java", "_shipment_8java.html", "_shipment_8java" ],
    [ "ShipmentStatus.java", "_shipment_status_8java.html", "_shipment_status_8java" ],
    [ "Species.java", "_species_8java.html", "_species_8java" ],
    [ "User.java", "_user_8java.html", "_user_8java" ]
];