var hierarchy =
[
    [ "com.spq.vinted.model.Ad", "classcom_1_1spq_1_1vinted_1_1model_1_1_ad.html", null ],
    [ "com.spq.vinted.controller.AdController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_ad_controller.html", null ],
    [ "com.spq.vinted.dto.AdDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_ad_d_t_o.html", null ],
    [ "com.spq.vinted.service.AdService", "classcom_1_1spq_1_1vinted_1_1service_1_1_ad_service.html", null ],
    [ "com.spq.vinted.controller.AuthenticationPrincipal", "interfacecom_1_1spq_1_1vinted_1_1controller_1_1_authentication_principal.html", null ],
    [ "com.spq.vinted.model.Category", "enumcom_1_1spq_1_1vinted_1_1model_1_1_category.html", null ],
    [ "com.spq.vinted.controller.ChatController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_chat_controller.html", null ],
    [ "com.spq.vinted.controller.ChatControllerTest", "classcom_1_1spq_1_1vinted_1_1controller_1_1_chat_controller_test.html", null ],
    [ "com.spq.vinted.dto.ChatMessageDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_chat_message_d_t_o.html", null ],
    [ "com.spq.vinted.dto.ChatMessageDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_chat_message_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.ChatRoom", "classcom_1_1spq_1_1vinted_1_1model_1_1_chat_room.html", null ],
    [ "com.spq.vinted.controller.ChatRoomController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_chat_room_controller.html", null ],
    [ "com.spq.vinted.dto.ChatRoomDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_chat_room_d_t_o.html", null ],
    [ "com.spq.vinted.dto.ChatRoomDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_chat_room_d_t_o_test.html", null ],
    [ "com.spq.vinted.dto.ChatRoomInfoDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_chat_room_info_d_t_o.html", null ],
    [ "com.spq.vinted.dto.ChatRoomInfoDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_chat_room_info_d_t_o_test.html", null ],
    [ "com.spq.vinted.service.ChatRoomService", "classcom_1_1spq_1_1vinted_1_1service_1_1_chat_room_service.html", null ],
    [ "com.spq.vinted.dto.ClothesDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_clothes_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.ClothesSize", "enumcom_1_1spq_1_1vinted_1_1model_1_1_clothes_size.html", null ],
    [ "com.spq.vinted.model.ClothesType", "enumcom_1_1spq_1_1vinted_1_1model_1_1_clothes_type.html", null ],
    [ "com.spq.vinted.dto.EditUserDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_edit_user_d_t_o_test.html", null ],
    [ "com.spq.vinted.dto.ElectronicsDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_electronics_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.ElectronicsType", "enumcom_1_1spq_1_1vinted_1_1model_1_1_electronics_type.html", null ],
    [ "com.spq.vinted.dto.EntertainmentDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_entertainment_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.EntertainmentType", "enumcom_1_1spq_1_1vinted_1_1model_1_1_entertainment_type.html", null ],
    [ "com.spq.vinted.dto.HomeDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_home_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.HomeType", "enumcom_1_1spq_1_1vinted_1_1model_1_1_home_type.html", null ],
    [ "com.spq.vinted.integration.IntegrationTest", "classcom_1_1spq_1_1vinted_1_1integration_1_1_integration_test.html", null ],
    [ "com.spq.vinted.model.Item", "classcom_1_1spq_1_1vinted_1_1model_1_1_item.html", [
      [ "com.spq.vinted.model.Clothes", "classcom_1_1spq_1_1vinted_1_1model_1_1_clothes.html", null ],
      [ "com.spq.vinted.model.Electronics", "classcom_1_1spq_1_1vinted_1_1model_1_1_electronics.html", null ],
      [ "com.spq.vinted.model.Entertainment", "classcom_1_1spq_1_1vinted_1_1model_1_1_entertainment.html", null ],
      [ "com.spq.vinted.model.Home", "classcom_1_1spq_1_1vinted_1_1model_1_1_home.html", null ],
      [ "com.spq.vinted.model.Pet", "classcom_1_1spq_1_1vinted_1_1model_1_1_pet.html", null ]
    ] ],
    [ "com.spq.vinted.controller.ItemController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_item_controller.html", null ],
    [ "com.spq.vinted.controller.ItemControllerTest", "classcom_1_1spq_1_1vinted_1_1controller_1_1_item_controller_test.html", null ],
    [ "com.spq.vinted.dto.ItemDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_item_d_t_o.html", [
      [ "com.spq.vinted.dto.ClothesDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_clothes_d_t_o.html", null ],
      [ "com.spq.vinted.dto.ElectronicsDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_electronics_d_t_o.html", null ],
      [ "com.spq.vinted.dto.EntertainmentDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_entertainment_d_t_o.html", null ],
      [ "com.spq.vinted.dto.HomeDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_home_d_t_o.html", null ],
      [ "com.spq.vinted.dto.PetDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_pet_d_t_o.html", null ]
    ] ],
    [ "com.spq.vinted.dto.ItemDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_item_d_t_o_test.html", null ],
    [ "com.spq.vinted.service.ItemService", "classcom_1_1spq_1_1vinted_1_1service_1_1_item_service.html", null ],
    [ "JpaRepository", null, [
      [ "com.spq.vinted.repository.AdRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_ad_repository.html", null ],
      [ "com.spq.vinted.repository.ChatRoomRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_chat_room_repository.html", null ],
      [ "com.spq.vinted.repository.ItemRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_item_repository.html", null ],
      [ "com.spq.vinted.repository.MessageRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_message_repository.html", null ],
      [ "com.spq.vinted.repository.OfferRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_offer_repository.html", null ],
      [ "com.spq.vinted.repository.PurchaseRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_purchase_repository.html", null ],
      [ "com.spq.vinted.repository.RatingRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_rating_repository.html", null ],
      [ "com.spq.vinted.repository.ShipmentRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_shipment_repository.html", null ],
      [ "com.spq.vinted.repository.UserRepository", "interfacecom_1_1spq_1_1vinted_1_1repository_1_1_user_repository.html", null ]
    ] ],
    [ "com.spq.vinted.dto.LoginDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_login_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.Message", "classcom_1_1spq_1_1vinted_1_1model_1_1_message.html", null ],
    [ "com.spq.vinted.service.MessageService", "classcom_1_1spq_1_1vinted_1_1service_1_1_message_service.html", null ],
    [ "com.spq.vinted.model.MessageTest", "classcom_1_1spq_1_1vinted_1_1model_1_1_message_test.html", null ],
    [ "com.spq.vinted.model.Message.MessageType", "enumcom_1_1spq_1_1vinted_1_1model_1_1_message_1_1_message_type.html", null ],
    [ "com.spq.vinted.model.Offer", "classcom_1_1spq_1_1vinted_1_1model_1_1_offer.html", null ],
    [ "com.spq.vinted.controller.OfferController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_offer_controller.html", null ],
    [ "com.spq.vinted.dto.OfferDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_offer_d_t_o.html", null ],
    [ "com.spq.vinted.dto.OfferDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_offer_d_t_o_test.html", null ],
    [ "com.spq.vinted.dto.OfferReturnerDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_offer_returner_d_t_o.html", null ],
    [ "com.spq.vinted.dto.OfferReturnerDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_offer_returner_d_t_o_test.html", null ],
    [ "com.spq.vinted.service.OfferService", "classcom_1_1spq_1_1vinted_1_1service_1_1_offer_service.html", null ],
    [ "com.spq.vinted.service.OfferServiceTest", "classcom_1_1spq_1_1vinted_1_1service_1_1_offer_service_test.html", null ],
    [ "com.spq.vinted.model.Offer.OfferStatus", "enumcom_1_1spq_1_1vinted_1_1model_1_1_offer_1_1_offer_status.html", null ],
    [ "com.spq.vinted.model.OfferTest", "classcom_1_1spq_1_1vinted_1_1model_1_1_offer_test.html", null ],
    [ "com.spq.vinted.dto.PaginatedResponseDTO< T >", "classcom_1_1spq_1_1vinted_1_1dto_1_1_paginated_response_d_t_o.html", null ],
    [ "com.spq.vinted.performance.PerformanceTest", "classcom_1_1spq_1_1vinted_1_1performance_1_1_performance_test.html", null ],
    [ "com.spq.vinted.dto.PetDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_pet_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.Purchase", "classcom_1_1spq_1_1vinted_1_1model_1_1_purchase.html", null ],
    [ "com.spq.vinted.controller.PurchaseController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_purchase_controller.html", null ],
    [ "com.spq.vinted.dto.PurchaseDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_purchase_d_t_o.html", null ],
    [ "com.spq.vinted.dto.PurchaseDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_purchase_d_t_o_test.html", null ],
    [ "com.spq.vinted.service.PurchaseService", "classcom_1_1spq_1_1vinted_1_1service_1_1_purchase_service.html", null ],
    [ "com.spq.vinted.model.Rating", "classcom_1_1spq_1_1vinted_1_1model_1_1_rating.html", null ],
    [ "com.spq.vinted.dto.RatingDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_rating_d_t_o.html", null ],
    [ "com.spq.vinted.dto.RatingDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_rating_d_t_o_test.html", null ],
    [ "com.spq.vinted.dto.RatingInfoDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_rating_info_d_t_o.html", null ],
    [ "com.spq.vinted.model.Shipment", "classcom_1_1spq_1_1vinted_1_1model_1_1_shipment.html", null ],
    [ "com.spq.vinted.controller.ShipmentController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_shipment_controller.html", null ],
    [ "com.spq.vinted.dto.ShipmentDTO", "classcom_1_1spq_1_1vinted_1_1dto_1_1_shipment_d_t_o.html", null ],
    [ "com.spq.vinted.service.ShipmentService", "classcom_1_1spq_1_1vinted_1_1service_1_1_shipment_service.html", null ],
    [ "com.spq.vinted.model.ShipmentStatus", "enumcom_1_1spq_1_1vinted_1_1model_1_1_shipment_status.html", null ],
    [ "com.spq.vinted.dto.SignupDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_signup_d_t_o_test.html", null ],
    [ "com.spq.vinted.model.Species", "enumcom_1_1spq_1_1vinted_1_1model_1_1_species.html", null ],
    [ "com.spq.vinted.model.User", "classcom_1_1spq_1_1vinted_1_1model_1_1_user.html", null ],
    [ "com.spq.vinted.controller.UserController", "classcom_1_1spq_1_1vinted_1_1controller_1_1_user_controller.html", null ],
    [ "com.spq.vinted.dto.UserDTOTest", "classcom_1_1spq_1_1vinted_1_1dto_1_1_user_d_t_o_test.html", null ],
    [ "com.spq.vinted.service.UserService", "classcom_1_1spq_1_1vinted_1_1service_1_1_user_service.html", null ],
    [ "com.spq.vinted.service.UserServiceTest", "classcom_1_1spq_1_1vinted_1_1service_1_1_user_service_test.html", null ],
    [ "com.spq.vinted.VintedApplication", "classcom_1_1spq_1_1vinted_1_1_vinted_application.html", null ],
    [ "com.spq.vinted.VintedApplicationTest", "classcom_1_1spq_1_1vinted_1_1_vinted_application_test.html", null ],
    [ "WebMvcConfigurer", null, [
      [ "com.spq.vinted.config.WebConfig", "classcom_1_1spq_1_1vinted_1_1config_1_1_web_config.html", null ]
    ] ],
    [ "WebSocketMessageBrokerConfigurer", null, [
      [ "com.spq.vinted.config.WebSocketConfig", "classcom_1_1spq_1_1vinted_1_1config_1_1_web_socket_config.html", null ]
    ] ]
];